"""Build and dispatch executive reports."""
from __future__ import annotations

from datetime import datetime, timezone

from jinja2 import Template
from sqlalchemy.orm import Session

from app import models
from app.agents.registry import get_agent
from app.config import settings
from app.services.email import send_email

_HTML = Template(
    """
<html><body style="font-family:Segoe UI,Arial,sans-serif;color:#1f2937;max-width:680px;margin:auto">
  <h2 style="color:#4f46e5">InfraMind — {{ title }}</h2>
  <p style="color:#6b7280">{{ generated }}</p>
  <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:16px">
    {{ narrative | replace('\n', '<br>') }}
  </div>
  <h3>Key metrics</h3>
  <ul>{% for f in facts %}<li>{{ f }}</li>{% endfor %}</ul>
  <h3>Top insights</h3>
  <table style="width:100%;border-collapse:collapse">
    <tr style="text-align:left;background:#eef2ff">
      <th style="padding:6px">Agent</th><th>Title</th><th>Severity</th><th>Impact</th>
    </tr>
    {% for i in insights %}
    <tr style="border-top:1px solid #e5e7eb">
      <td style="padding:6px">{{ i.agent }}</td><td>{{ i.title }}</td>
      <td>{{ i.severity }}</td><td>${{ '%.0f' % i.impact_usd }}</td>
    </tr>
    {% endfor %}
  </table>
  <p style="color:#9ca3af;font-size:12px;margin-top:24px">
    Generated by InfraMind autonomous agents.
  </p>
</body></html>
"""
)


def build_weekly_report(db: Session) -> models.Report:
    exec_agent = get_agent("executive")
    result = exec_agent.analyze(db)

    top_insights = (
        db.query(models.Insight)
        .order_by(models.Insight.impact_usd.desc())
        .limit(8)
        .all()
    )
    insights_view = [
        {"agent": i.agent, "title": i.title, "severity": i.severity, "impact_usd": i.impact_usd}
        for i in top_insights
    ]

    title = "Weekly Infrastructure Intelligence Report"
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    html = _HTML.render(
        title=title,
        generated=generated,
        narrative=result.narrative,
        facts=result.facts,
        insights=insights_view,
    )
    text = result.narrative + "\n\nKey metrics:\n" + "\n".join(f"- {f}" for f in result.facts)

    recipients = settings.recipients_list
    sent = send_email(f"InfraMind — {title}", html, text, recipients)

    report = models.Report(
        kind="weekly",
        title=title,
        body_html=html,
        body_text=text,
        recipients=", ".join(recipients),
        sent=1 if sent else 0,
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    return report
